default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: committed
        name: Lint commit message
        entry: committed
        language: system
        files: .*
        args: [--fixup, --wip, --commit-file]
        stages: [commit-msg]

      - id: fmt
        name: Lint Check
        entry: cargo
        language: system
        files: .*
        args: [fmt, --check]
        pass_filenames: false
        stages: [commit]

      - id: clippy
        name: Check clippy suggestions
        entry: cargo
        language: system
        files: .*
        args: [clippy]
        pass_filenames: false
        stages: [commit]
