default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        stages: [commit]

  - repo: local
    hooks:
      - id: committed
        name: Lint commit message
        entry: committed
        language: system
        files: .*
        args: [--fixup, --wip, --commit-file]
        stages: [commit-msg]

      - id: typos
        name: Check for typos
        entry: typos
        language: system
        files: .*
        stages: [commit]

  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.0
    hooks:
      - id: fmt
        stages: [commit]
      - id: clippy
        stages: [commit]
