name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --current -vv --strip header
        env:
          OUTPUT: BODY.md

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./target/release/rofi-obsidian
          bodyFile: BODY.md
