name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --release --verbose

      - name: Publish on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --allow-dirty --token ${{ secrets.CARGO_TOKEN }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --latest -vv --strip header
        env:
          OUTPUT: BODY.md

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./target/release/rofi-obsidian
          bodyFile: BODY.md
          allowUpdates: true
