name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: -l --strip header
        env:
          OUTPUT: ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/rofi-obsidian
          body_path: ${{ github.workspace }}-CHANGELOG.txt
