name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/rofi-obsidian
